version: "3"
services:
#  mysql:
#    image: mysql
#    environment:
#      MYSQL_DATABASE: gangnam_portal
#      MYSQL_ROOT_PASSWORD: 1234
#      MYSQL_ROOT_HOST: '%'
#    ports:
#      - 3307:3307
#
#  redis:
#    image: redis
#    ports:
#      - 6379:6379

  gangnam_portal:
    build: .
    ports:
      - 8080:8080
#    depends_on:
#      - mysql
#      - redis

